
import asyncio
import httpx
import sys
import os

# Ensure we can import app
sys.path.append(os.getcwd())

from app.db.mongodb import init_db
from app.models.user import User, UserRole
from app.models.lawyer import LawyerProfile
from app.core.security import get_password_hash

async def create_test_data():
    email = "lawyer_api_tester@example.com"
    password = "password123"
    
    # 1. Create/Get User
    user = await User.find_one(User.email == email)
    if not user:
        print(f"Creating user {email}...")
        user = User(
            email=email,
            hashed_password=get_password_hash(password),
            full_name="Auto Test Lawyer",
            phone="+919988776655", # valid 10 digit
            role=UserRole.LAWYER,
            is_active=True
        )
        await user.insert()
    else:
        print(f"User {email} exists.")
        user.hashed_password = get_password_hash(password)
        user.role = UserRole.LAWYER # Ensure role
        await user.save()

    # 2. Create/Get LawyerProfile
    profile = await LawyerProfile.find_one(LawyerProfile.user_id == user.id)
    if not profile:
        print("Creating lawyer profile...")
        profile = LawyerProfile(
            user_id=user.id,
            specialization=["Property"],
            experience_years=5,
            cities=["Bangalore"],
            notification_preferences={"email_notifications": True}
        )
        await profile.insert()
        user.lawyer_profile_id = profile.id
        await user.save()
    else:
        print("Lawyer profile exists.")

    return email, password

async def run_tests():
    print("Initializing Database connection...")
    await init_db()
    
    email, password = await create_test_data()
    
    base_url = "http://127.0.0.1:8000/api/v1"
    
    async with httpx.AsyncClient(base_url=base_url) as client:
        # A. Login
        print("\n[TEST] Login...")
        resp = await client.post("/lawyer/auth/login", data={"username": email, "password": password})
        if resp.status_code != 200:
            print(f"FAILED: Login failed: {resp.text}")
            return
        token = resp.json()["access_token"]
        headers = {"Authorization": f"Bearer {token}"}
        print("SUCCESS: Login successful.")

        # B. Dashboard
        print("\n[TEST] Get Dashboard (Check Earnings)...")
        resp = await client.get("/lawyer/dashboard", headers=headers)
        if resp.status_code == 200:
            data = resp.json()
            earnings_text = data.get('earnings', {}).get('total_earnings')
            print(f"SUCCESS: Dashboard Earnings: {earnings_text.encode('ascii', 'ignore').decode('ascii')}")
        else:
            print(f"FAILED: Dashboard failed: {resp.status_code} - {resp.text}")

        # C. Clients - Create Lead
        print("\n[TEST] Create Client Lead with Fees...")
        lead_data = {
            "client_name": "API Test Client",
            "client_phone": "9876543210",
            "service_fee": 7500.0,
            "service_type": "Legal Consultation",
            "notes": "Generated by test script"
        }
        resp = await client.post("/lawyer/clients", json=lead_data, headers=headers)
        if resp.status_code == 200:
            lead = resp.json()
            print(f"DEBUG Response: {lead}")
            print(f"SUCCESS: Lead created with ID: {lead.get('id')}")
            print(f"SUCCESS: Lead Service Fee: {lead.get('service_fee')}")
            if lead.get('service_fee') == 7500.0:
                print("VERIFIED: Service Fee mapped correctly.")
            else:
                print("FAILED: Service Fee mismatch.")
        else:
            print(f"FAILED: Create Lead failed: {resp.status_code} - {resp.text}")

        # D. Settings - Update
        print("\n[TEST] Update Settings (Dynamic Prefs)...")
        update_data = {
            "notification_preferences": {"email_notifications": False, "case_updates": True}
        }
        resp = await client.patch("/lawyer/settings/profile", json=update_data, headers=headers)
        if resp.status_code == 200:
            print("SUCCESS: Settings updated.")
            # Verify update
            resp = await client.get("/lawyer/settings", headers=headers)
            prefs_list = resp.json().get("notification_preferences", [])
            
            # Helper to find pref
            def get_pref(pid):
                for p in prefs_list:
                    if p['id'] == pid: return p['enabled']
                return None
            
            email_pref = get_pref("email_notifications")
            case_pref = get_pref("case_updates")
            
            print(f"VERIFIED: email_notifications={email_pref} (Expected False)")
            print(f"VERIFIED: case_updates={case_pref} (Expected True)")
            
            if email_pref is False and case_pref is True:
                print("SUCCESS: Notification preferences persisted correctly.")
            else:
                print("FAILED: Persistence check failed.")

        else:
            print(f"FAILED: Update Settings failed: {resp.status_code} - {resp.text}")
            
        # E. Verify Dashboard Earnings Update?
        # Since we added a lead but didn't set it to PAID, earnings might not change.
        # But checking dashboard logic: payment_status must be PAID.
        # So it shouldn't change.
        # Let's verify that.
        
        # F. Schedule
        print("\n[TEST] Get Schedule (Verify Mock Data Gone)...")
        resp = await client.get("/lawyer/schedule", headers=headers)
        if resp.status_code == 200:
            data = resp.json()
            today = data.get("today", [])
            print(f"Today's Events: {len(today)}")
            # If mock data was "Court Hearing" with ID "mock_court", check if it exists
            mock_found = any(e['id'] == 'mock_court' for e in today)
            if not mock_found:
                 print("SUCCESS: No mock events found (unless specifically added).")
            else:
                 print("WARNING: Mock event 'mock_court' still present.")
        else:
            print(f"FAILED: Get Schedule failed: {resp.status_code} - {resp.text}")

if __name__ == "__main__":
    asyncio.run(run_tests())
