"""API v1 endpoints"""

__all__ = [
    "public_auth",
    "admin_auth",
    "developers",
    "users",
    "public_projects",
    "developer_projects",
    "admin_projects",
    "developer_leads",
    "admin_change_requests",
    "developer_webhooks",
    "user_interactions",
    "user_portal",
    "admin_settings",
    "developer_team",
    "admin_subscriptions",
    "developer_subscriptions",
    "admin_dashboard",
    "admin_analytics",
    "admin_ads",
    "admin_team",
    "admin_landmarks",
    "admin_videos",
    "locality",
    "developer_uploads",
    "developer_auth",
    "lawyer_auth",
    "lawyer_dashboard",
    "lawyer_cases",
    "lawyer_clients",
    "lawyer_schedule",
    "lawyer_analytics",
    "lawyer_settings",
    "wishlist",
    "public_home",
    "admin_blogs",
    "admin_reels",
    "user_reels",
    "admin_cities"

]
